# Dockerfile for Nginx
FROM nginx:alpine

# Copy custom Nginx configuration
COPY ./docker/nginx/nginx.conf /etc/nginx/conf.d/default.conf

# Set working directory
WORKDIR /var/www

# Expose port 80
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
