services:
    # deploy
#    app:
#        build:
#            context: .
#            dockerfile: Dockerfile.phpfpm.deploy
#        container_name: phpfpm-deploy
#        networks:
#            - laravel
#        depends_on:
#            - redis
    # local
    app:
        image: phpfpm-local
        container_name: phpfpm-local
        working_dir: /var/www
        volumes:
            - .:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
            - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
        command: ["sh", "-c", "./docker/local_process.sh && php-fpm"]
        networks:
            - laravel
        depends_on:
            - redis

    web:
        build:
            context: .
            dockerfile: Dockerfile.nginx
        container_name: nginx
        working_dir: /var/www
#        volumes:
#            - .:/var/www
#            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8080:80"
        networks:
            - laravel
        depends_on:
            - app

#    db:
#        image: mysql:8.0
#        container_name: mysql
#        environment:
#            MYSQL_ROOT_PASSWORD: root
#            MYSQL_DATABASE: laravel
#            MYSQL_USER: user
#            MYSQL_PASSWORD: password
#        volumes:
#            - dbdata:/var/lib/mysql
#        networks:
#            - laravel
#        ports:
#            - "3306:3306"

    redis:
        image: redis:alpine
        container_name: redis
        networks:
            - laravel
        ports:
            - "6379:6379"

volumes:
    dbdata:

networks:
    laravel:
        driver: bridge
